module.exports = {
	"extends": [
		"./.eslintrc.js",
	],
	"globals": {
		"LibraryManager": true,
		"mergeInto": true,
		"autoAddDeps": true,
		"HEAP8": true,
		"HEAPU8": true,
		"HEAP32": true,
		"HEAPF32": true,
		"ERRNO_CODES": true,
		"FS": true,
		"IDBFS": true,
		"FoxOS": true,
		"FoxConfig": true,
		"FoxRuntime": true,
		"FoxFS": true,
		"IDHandler": true,
		"Browser": true,
		"GL": true,
		"XRWebGLLayer": true,
	},
};
