blank_issues_enabled: false

contact_links:
  - name: Fox proposals
    url: https://github.com/Foxengine/Fox-proposals
    about: Please submit feature proposals on the Fox proposals repository, not here.

  - name: Fox documentation repository
    url: https://github.com/Foxengine/Fox-docs
    about: Please report issues with documentation on the Fox documentation repository, not here.

  - name: Fox community channels
    url: https://godotengine.org/community
    about: Please ask for technical support on one of the other community channels, not here.
